# Generated by Django 5.0.4 on 2024-04-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='games',
            options={'verbose_name': 'Game'},
        ),
        migrations.AlterField(
            model_name='games',
            name='release_year',
            field=models.DateField(),
        ),
    ]
